version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sqs,dynamodb
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "./localstack:/etc/localstack/init/ready.d"
      - "/var/run/docker.sock:/var/run/docker.sock"

  ms-video:
    build:
      context: .
    ports:
      - "8082:8080"
    environment:
      - AWS_REGION=us-east-1
      - STAGE=dev
      - AWS_ENDPOINT_URL=http://localstack:4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - SQS_QUEUE_URL=http://localstack:4566/000000000000/MSVideo-Queue
      - JWT_SECRET=your-secret-key-change-in-production
      - PORT=8080
      - MS_NOTIFY_URL=http://ms-notify:8080
    depends_on:
      - localstack
