# Ingress path-based para ms-auth, ms-video, ms-notify. ALB criado pelo AWS Load Balancer Controller (Entrega 6).
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: video-system
  namespace: video-system
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: ms-auth
                port:
                  number: 8080
          - path: /video
            pathType: Prefix
            backend:
              service:
                name: ms-video
                port:
                  number: 8080
          - path: /notify
            pathType: Prefix
            backend:
              service:
                name: ms-notify
                port:
                  number: 8080
