# Overlay prod â€” EKS com imagens ECR. Ajuste as URLs nos patches com os outputs do Terraform (ecr_repository_urls).
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: video-system

resources:
  - ../../base
  - namespace.yaml
  - ingress.yaml
  - servicemonitor-video-system.yaml
  - sa-ms-notify.yaml

patches:
  - path: patch-ms-auth-image.yaml
    target:
      kind: Deployment
      name: ms-auth
  - path: patch-ms-video-image.yaml
    target:
      kind: Deployment
      name: ms-video
  - path: patch-ms-notify-image.yaml
    target:
      kind: Deployment
      name: ms-notify
