apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-video
spec:
  template:
    spec:
      serviceAccountName: app
      containers:
        - name: ms-video
          image: 027653366477.dkr.ecr.us-east-1.amazonaws.com/ms-video:7be192c36a2be4307b3c40de1862133b31973858
          imagePullPolicy: Always
