apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-auth
spec:
  template:
    spec:
      serviceAccountName: app
      containers:
        - name: ms-auth
          image: 027653366477.dkr.ecr.us-east-1.amazonaws.com/ms-auth:1e2fb8daee35b7ecd677ea320c0e5404899e0264
          imagePullPolicy: Always
          env:
            - name: SERVICE_NAME
              value: "ms-auth"
            - name: PORT
              value: "8080"
            - name: JWT_SECRET
              value: "your-secret-key-change-in-production"
            - name: JWT_EXPIRATION_HOURS
              value: "24"