apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-video
spec:
  template:
    spec:
      serviceAccountName: app
      containers:
        - name: ms-video
          image: 027653366477.dkr.ecr.us-east-1.amazonaws.com/ms-video:1e2fb8daee35b7ecd677ea320c0e5404899e0264
          imagePullPolicy: Always
